version: 2

builds:
  - id: mailerlite
    binary: mailerlite
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/mailerlite/mailerlite-cli/cmd.version={{.Version}}
      - -X github.com/mailerlite/mailerlite-cli/cmd.commit={{.ShortCommit}}
      - -X github.com/mailerlite/mailerlite-cli/cmd.date={{.Date}}
    hooks:
      post:
        - cmd: ./scripts/sign-macos.sh "{{ .Os }}" "{{ .Path }}" "{{ .IsSnapshot }}"
          output: true

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc

homebrew_casks:
  - name: mailerlite
    binaries:
      - mailerlite
    homepage: "https://github.com/mailerlite/mailerlite-cli"
    description: "Command-line interface for the MailerLite API"
    directory: Casks
    repository:
      owner: mailerlite
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
